---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apm.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.service.port }}
    - name: jaeger-grpc
      port: 14250
      protocol: TCP
      targetPort: jaeger-grpc
    - name: jaeger-http
      port: 14268
      protocol: TCP
      targetPort: jaeger-http
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
